# Generated by Django 5.0.3 on 2024-05-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_skinimage_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skinimage',
            old_name='profile',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
