# Generated by Django 5.0.3 on 2024-06-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appointment_contactform_delete_classificationresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkinImage',
        ),
    ]
