# Generated by Django 5.0.3 on 2024-06-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profileuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
