# Generated by Django 5.0.3 on 2024-06-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_profileuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='skin_images/profile_pic/'),
        ),
    ]
