# Generated by Django 5.0.3 on 2024-06-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profileuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='profile_pic',
        ),
    ]
